#!/bin/bash
#
# Expected flow
# Check last commit message
# | if "uncomplete" or "wip"
#     | uncommit changes
#     | push to remote
#     | commit changes with message
#     | push to remote
#
# | if other
#     | do nothing

. $DOT/utils/print_functions.sh

last_commit=$(GIT_PAGER=/usr/bin/less git show --pretty=format:"%s" -s HEAD)
message=$1

info "Checking commit message"
if [[ "$last_commit" == "wip" || "$last_commit" == "uncomplete" ]]; then
  success "Commit message checked wip commit found"
else
  fail "Last commit message isn't 'uncomplete' or 'wip' aborting to reset commit"
  exit 1
fi


info "Reseting commit"
if git reset --mixed --quiet HEAD^1; then
  success "Uncompleted changes reseted"
else
  fail "Failed to Reset commit"
  exit 1
fi

info "Sending reset to remote"
if git push origin +HEAD --quiet; then
  success "Revert last commit from remote"
else
  fail "Failed to push revert commit"
  exit 1
fi

info "Creating commit"
if git ac "$message" --quiet; then
  success "Commit created"
else
  fail "Failed to commit"
  exit 1
fi

info "Pusing changes to remote"
if git push origin --quiet; then
  success "Completed changes pushed to remote"
else
  fail "Failed to push revert commit"
  exit 1
fi

