format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$fill\
$cmd_duration $jobs $nodejs $sudo\
$line_break\
$character"""

add_newline = false

[fill]
symbol = " "

[directory]
style = "bold cyan"
read_only = " ðŸ”’"
truncation_length = 4
truncate_to_repo = false
home_symbol = "~"

[character]
success_symbol = "[Î»](green)"
error_symbol = "[Î»](red)"

[git_branch]
symbol = "î‚  "
format = "[$symbol$branch]($style) "
style = "bright-red"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "white"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[jobs]
symbol = "âœ¦"
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[nodejs]
symbol = ""
